/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── CSS custom properties (light/dark switch via .dark class) ──
        primary: {
          DEFAULT: 'rgb(var(--c-primary) / <alpha-value>)',
          container: 'rgb(var(--c-primary-container) / <alpha-value>)',
          fixed: 'rgb(var(--c-primary-fixed) / <alpha-value>)',
          'fixed-dim': 'rgb(var(--c-primary-fixed-dim) / <alpha-value>)',
          dark: 'rgb(var(--c-primary-dark) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'rgb(var(--c-secondary) / <alpha-value>)',
          container: 'rgb(var(--c-secondary-container) / <alpha-value>)',
          fixed: 'rgb(var(--c-secondary-fixed) / <alpha-value>)',
          'fixed-dim': 'rgb(var(--c-secondary-fixed-dim) / <alpha-value>)',
        },
        surface: {
          DEFAULT: 'rgb(var(--c-surface) / <alpha-value>)',
          bright: 'rgb(var(--c-surface-bright) / <alpha-value>)',
          dim: 'rgb(var(--c-surface-dim) / <alpha-value>)',
          container: {
            DEFAULT: 'rgb(var(--c-surface-container) / <alpha-value>)',
            low: 'rgb(var(--c-surface-container-low) / <alpha-value>)',
            lowest: 'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
            high: 'rgb(var(--c-surface-container-high) / <alpha-value>)',
            highest: 'rgb(var(--c-surface-container-highest) / <alpha-value>)',
          },
          tint: 'rgb(var(--c-surface-tint) / <alpha-value>)',
          variant: 'rgb(var(--c-surface-variant) / <alpha-value>)',
        },
        'on-surface': 'rgb(var(--c-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        outline: {
          DEFAULT: 'rgb(var(--c-outline) / <alpha-value>)',
          variant: 'rgb(var(--c-outline-variant) / <alpha-value>)',
        },
        'inverse-surface': 'rgb(var(--c-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--c-inverse-primary) / <alpha-value>)',
        error: {
          DEFAULT: 'rgb(var(--c-error) / <alpha-value>)',
          container: 'rgb(var(--c-error-container) / <alpha-value>)',
        },
        tertiary: {
          DEFAULT: 'rgb(var(--c-tertiary) / <alpha-value>)',
          container: 'rgb(var(--c-tertiary-container) / <alpha-value>)',
          fixed: 'rgb(var(--c-tertiary-fixed) / <alpha-value>)',
          'fixed-dim': 'rgb(var(--c-tertiary-fixed-dim) / <alpha-value>)',
        },
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['2.75rem', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-sm': ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['2rem', { lineHeight: '1.25', fontWeight: '700' }],
        'headline-md': ['1.75rem', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        'title-lg': ['1.375rem', { lineHeight: '1.45', fontWeight: '500' }],
        'title-md': ['1.125rem', { lineHeight: '1.5', fontWeight: '500' }],
        'title-sm': ['0.9375rem', { lineHeight: '1.55', fontWeight: '500' }],
        'body-lg': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['0.875rem', { lineHeight: '1.55', fontWeight: '400' }],
        'body-sm': ['0.75rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['0.875rem', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.006em' }],
        'label-md': ['0.75rem', { lineHeight: '1.35', fontWeight: '500', letterSpacing: '0.05em' }],
        'label-sm': ['0.6875rem', { lineHeight: '1.3', fontWeight: '500', letterSpacing: '0.05em' }],
      },
      borderRadius: {
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
        '2xl': '32px',
      },
      boxShadow: {
        'ambient': '0 12px 40px rgba(25, 28, 30, 0.04)',
        'ambient-md': '0 8px 24px rgba(25, 28, 30, 0.08)',
        'ambient-lg': '0 16px 48px rgba(25, 28, 30, 0.12)',
        'ambient-xl': '0 24px 64px rgba(25, 28, 30, 0.16)',
        'card': '0 2px 8px rgba(25, 28, 30, 0.04), 0 8px 24px rgba(25, 28, 30, 0.04)',
        'card-hover': '0 8px 24px rgba(25, 28, 30, 0.08), 0 24px 48px rgba(0, 104, 95, 0.08)',
        'glass': '0 4px 24px rgba(25, 28, 30, 0.08)',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        float: { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-8px)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        pulse: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.6s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
      },
      backdropBlur: { 'xs': '4px', 'glass': '20px' },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
